[theme]
# Primary accent color for interactive elements.
primaryColor = "#A4A4A5"

# Background color for the main content area.
backgroundColor = "#1C1C1C"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#586e75"

# Color used for almost all text.
textColor = "#fff"